sudo: required
services:
  - docker

before_install:
  - docker build -t aidandang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aidandang/docker-react npm run test -- --coverage
